// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS_1_Backend.Data;

#nullable disable

namespace PS_1_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714030413_AddCHONameToInsertActivity")]
    partial class AddCHONameToInsertActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PS_1_Backend.Models.CHO_Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ANM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ASHA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Financial_Month_List")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Finanicial_Year_list")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSc_List")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CHO_Activities");
                });

            modelBuilder.Entity("PS_1_Backend.Models.Insert_Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CHO_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Denominator")
                        .HasColumnType("int");

                    b.Property<int>("Numerator")
                        .HasColumnType("int");

                    b.Property<string>("Source_of_Verification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Work_Percentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Insert_Activities");
                });

            modelBuilder.Entity("PS_1_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
